var NOKIY_APP_RECORDS = [
  CNAME("auth.synapse", "mine.nokiy.net."),
  CNAME("backup", "backup-nokiy-net.fly.storage.tigris.dev."),
  CNAME("demo.cvpage", "reonokiy.github.io."),
  CNAME("elk", "949e3763b88b2f0b.vercel-dns-017.com."),
  CNAME("file.git", "git-nokiy-net.fly.storage.tigris.dev."),
  CNAME("file", "file-nokiy-net.pages.dev.", CF_PROXY_ON),
  CNAME("file.self", "self-nokiy-net.fly.storage.tigris.dev."),
  CNAME("file.social", "social-nokiy-net.fly.storage.tigris.dev."),
  CNAME("gateway.nexal", "nexal.fly.dev."),
  CNAME("obsidian", "obsidian-nokiy-net.fly.storage.tigris.dev."),
  CNAME("paper", "paper-nokiy-net.pages.dev.", CF_PROXY_ON),
  CNAME("public", "public-nokiy-net.fly.storage.tigris.dev."),
  CNAME("simple-backup", "reonokiy.github.io."),
  CNAME("storage.base", "storage-base-nokiy-net.fly.storage.tigris.dev."),
  CNAME("synapse", "mine.nokiy.net."),
  CNAME("telemetry-storage", "telemetry-storage-nokiy-net.fly.storage.tigris.dev."),
  CNAME("test", "noki.nokiy.net."),
];
