D("nokiy.net", REG_NONE, DnsProvider(CF),
  DefaultTTL(1),
  CF_MANAGE_COMMENTS,

  NOKIY_HOST_RECORDS,
  NOKIY_INTERNAL_RECORDS,
  NOKIY_APP_RECORDS,
  NOKIY_MAIL_RECORDS,
  NOKIY_VERIFICATION_RECORDS,
  NOKIY_DELEGATION_RECORDS,
  NOKIY_EXTERNAL_DNS_IGNORES,
);
